import { type UiThemePresetName, type UiThemeVars } from '@/styles/theme/themeKeys.ts';

export interface UiThemePreset {
    name: UiThemePresetName;
    label: string;
    light: UiThemeVars;
    dark: UiThemeVars;
}

export const presets: Record<UiThemePresetName, UiThemePreset> = {
    default: {
        name: 'default',
        label: '默认',
        light: {
            bodyColor: '#f6f9fd',
            bodyGradientStart: '#f7fbff',
            bodyGradientEnd: '#eef6ff',
            primaryColor: '#2f6db5',
            primaryColorHover: '#4b83c2',
            primaryColorPressed: '#1f4f8f',
            primaryColorSuppl: '#8ab7dd',
            cardColor: '#ffffff',
            translucentCardColor: 'rgba(255, 255, 255, 0.78)',
            cardTitleColor: '#10233f',
            textColor: '#10233f',
            secondaryTextColor: '#475569',
            mutedTextColor: '#64748b',
            borderColor: 'rgba(47, 109, 181, 0.1)',
            panelColor: 'rgba(47, 109, 181, 0.08)',
            controlColor: '#ffffff',
            controlColorFocus: '#ffffff',
            controlColorDisabled: '#f1f5f9',
            controlTextColor: '#10233f',
            controlPlaceholderColor: '#94a3b8',
            controlBorderColor: 'rgba(47, 109, 181, 0.18)',
            controlBorderHoverColor: 'rgba(47, 109, 181, 0.36)',
            controlBorderFocusColor: '#2f6db5',
            controlTagColor: 'rgba(47, 109, 181, 0.1)',
            controlTagTextColor: '#10233f',
            sliderRailColor: 'rgba(47, 109, 181, 0.12)',
            sliderRailHoverColor: 'rgba(47, 109, 181, 0.18)',
            sliderFillColor: '#2f6db5',
            sliderFillHoverColor: '#4b83c2',
            sliderHandleColor: '#ffffff',
            backTopColor: 'rgba(255, 255, 255, 0.9)',
            backTopHoverColor: '#ffffff',
            backTopIconColor: '#2f6db5',
            backTopIconHoverColor: '#4b83c2',
            codeBackgroundColor: '#f1f5f9',
            codeTextColor: '#e11d48',
            codeTheme: 'light',
            inlineCodeBackgroundColor: '#f1f5f9',
            inlineCodeTextColor: '#e11d48',
            markBackgroundColor: 'rgba(47, 109, 181, 0.14)',
            tableHeaderColor: 'rgba(47, 109, 181, 0.08)',
            scrollbarTrackColor: '#f1f5f9',
            scrollbarThumbColor: '#94a3b8',
            copyButtonBackgroundColor: 'rgba(255, 255, 255, 0.78)',
            copyButtonTextColor: '#10233f',
            footerTextColor: '#10233f',
            linkColor: '#2f6db5',
            linkHoverColor: '#4b83c2',
            infoColor: '#7da7ff',
            successColor: '#4dd27a',
            warningColor: '#ffb454',
            errorColor: '#d03050',
            alertInfoBackgroundColor: 'rgba(125, 167, 255, 0.14)',
            alertSuccessBackgroundColor: 'rgba(77, 210, 122, 0.14)',
            alertWarningBackgroundColor: 'rgba(255, 180, 84, 0.18)',
            alertErrorBackgroundColor: 'rgba(208, 48, 80, 0.12)',
            orangeColor: '#ff6200',
            cyanColor: '#00aaff',
            mutedAccentColor: '#94a3b8',
            cardShadow: '0 14px 36px rgba(47, 109, 181, 0.08)',
            elevatedShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
            focusRingShadow: '0 0 0 4px rgba(47, 109, 181, 0.12)',
            cardRadius: '6px',
            pillRadius: '999px',
            iconColor: '#2f6db5',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#667eea',
            categorySolutionColor: '#f39c12',
            categoryTechColor: '#e74c3c',
            categoryAlgorithmColor: '#3498db',
            categoryLifeColor: '#2ecc71',
            categoryStudyColor: '#9b59b6',
            categoryFunColor: '#1abc9c',
            categoryChatColor: '#34495e',
            categoryUnknownColor: '#95a5a6'
        },
        dark: {
            bodyColor: '#0f1219',
            bodyGradientStart: '#131825',
            bodyGradientEnd: '#0d1017',
            primaryColor: '#5b9bd5',
            primaryColorHover: '#7db3e0',
            primaryColorPressed: '#3a7cc0',
            primaryColorSuppl: '#2a5a8a',
            cardColor: '#1a2030',
            translucentCardColor: 'rgba(26, 32, 48, 0.82)',
            cardTitleColor: '#e2e8f0',
            textColor: '#e2e8f0',
            secondaryTextColor: '#cbd5e1',
            mutedTextColor: '#94a3b8',
            borderColor: 'rgba(91, 155, 213, 0.15)',
            panelColor: 'rgba(91, 155, 213, 0.08)',
            controlColor: '#151b29',
            controlColorFocus: '#1a2030',
            controlColorDisabled: '#111827',
            controlTextColor: '#e2e8f0',
            controlPlaceholderColor: '#64748b',
            controlBorderColor: 'rgba(91, 155, 213, 0.24)',
            controlBorderHoverColor: 'rgba(91, 155, 213, 0.44)',
            controlBorderFocusColor: '#5b9bd5',
            controlTagColor: 'rgba(91, 155, 213, 0.14)',
            controlTagTextColor: '#e2e8f0',
            sliderRailColor: 'rgba(148, 163, 184, 0.22)',
            sliderRailHoverColor: 'rgba(148, 163, 184, 0.32)',
            sliderFillColor: '#5b9bd5',
            sliderFillHoverColor: '#7db3e0',
            sliderHandleColor: '#e2e8f0',
            backTopColor: 'rgba(26, 32, 48, 0.92)',
            backTopHoverColor: '#222a3d',
            backTopIconColor: '#cbd5e1',
            backTopIconHoverColor: '#7db3e0',
            codeBackgroundColor: '#1e2536',
            codeTextColor: '#fb7185',
            codeTheme: 'dark',
            inlineCodeBackgroundColor: '#1e2536',
            inlineCodeTextColor: '#fb7185',
            markBackgroundColor: 'rgba(91, 155, 213, 0.18)',
            tableHeaderColor: 'rgba(91, 155, 213, 0.08)',
            scrollbarTrackColor: '#1e2536',
            scrollbarThumbColor: '#64748b',
            copyButtonBackgroundColor: 'rgba(26, 32, 48, 0.82)',
            copyButtonTextColor: '#e2e8f0',
            footerTextColor: '#e2e8f0',
            linkColor: '#5b9bd5',
            linkHoverColor: '#7db3e0',
            infoColor: '#7db3e0',
            successColor: '#4dd27a',
            warningColor: '#ffb454',
            errorColor: '#fb7185',
            alertInfoBackgroundColor: 'rgba(125, 179, 224, 0.16)',
            alertSuccessBackgroundColor: 'rgba(77, 210, 122, 0.16)',
            alertWarningBackgroundColor: 'rgba(255, 180, 84, 0.2)',
            alertErrorBackgroundColor: 'rgba(251, 113, 133, 0.16)',
            orangeColor: '#ff944d',
            cyanColor: '#38bdf8',
            mutedAccentColor: '#64748b',
            cardShadow: '0 14px 36px rgba(0, 0, 0, 0.35)',
            elevatedShadow: '0 4px 12px rgba(0, 0, 0, 0.5)',
            focusRingShadow: '0 0 0 4px rgba(91, 155, 213, 0.15)',
            cardRadius: '6px',
            pillRadius: '999px',
            iconColor: '#5b9bd5',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#8ea2ff',
            categorySolutionColor: '#fbbf24',
            categoryTechColor: '#f87171',
            categoryAlgorithmColor: '#60a5fa',
            categoryLifeColor: '#4ade80',
            categoryStudyColor: '#c084fc',
            categoryFunColor: '#2dd4bf',
            categoryChatColor: '#94a3b8',
            categoryUnknownColor: '#94a3b8'
        }
    },

    modern: {
        name: 'modern',
        label: '现代',
        light: {
            bodyColor: '#f5f5f7',
            bodyGradientStart: '#f5f5f7',
            bodyGradientEnd: '#f5f5f7',
            primaryColor: '#2f6db5',
            primaryColorHover: '#3d7cc4',
            primaryColorPressed: '#275d9e',
            primaryColorSuppl: '#6d9ecf',
            cardColor: '#ffffff',
            translucentCardColor: '#ffffff',
            cardTitleColor: '#18181b',
            textColor: '#27272a',
            secondaryTextColor: '#52525b',
            mutedTextColor: '#71717a',
            borderColor: '#e8e8ec',
            panelColor: '#f4f4f5',
            controlColor: '#ffffff',
            controlColorFocus: '#ffffff',
            controlColorDisabled: '#f4f4f5',
            controlTextColor: '#27272a',
            controlPlaceholderColor: '#a1a1aa',
            controlBorderColor: '#d9d9de',
            controlBorderHoverColor: '#a1a1aa',
            controlBorderFocusColor: '#2f6db5',
            controlTagColor: '#f4f4f5',
            controlTagTextColor: '#3f3f46',
            sliderRailColor: '#e4e4e7',
            sliderRailHoverColor: '#d4d4d8',
            sliderFillColor: '#2f6db5',
            sliderFillHoverColor: '#3d7cc4',
            sliderHandleColor: '#ffffff',
            backTopColor: '#ffffff',
            backTopHoverColor: '#f4f4f5',
            backTopIconColor: '#52525b',
            backTopIconHoverColor: '#2f6db5',
            codeBackgroundColor: '#f6f7f9',
            codeTextColor: '#be185d',
            codeTheme: 'light',
            inlineCodeBackgroundColor: '#f4f4f5',
            inlineCodeTextColor: '#be185d',
            markBackgroundColor: '#dcebfb',
            tableHeaderColor: '#fafafa',
            scrollbarTrackColor: '#f4f4f5',
            scrollbarThumbColor: '#d4d4d8',
            copyButtonBackgroundColor: '#ffffff',
            copyButtonTextColor: '#3f3f46',
            footerTextColor: '#71717a',
            linkColor: '#2f6db5',
            linkHoverColor: '#3d7cc4',
            infoColor: '#3f76c9',
            successColor: '#15803d',
            warningColor: '#b45309',
            errorColor: '#dc2626',
            alertInfoBackgroundColor: '#eef4fc',
            alertSuccessBackgroundColor: '#effaf1',
            alertWarningBackgroundColor: '#fdf6e8',
            alertErrorBackgroundColor: '#fdf0f0',
            orangeColor: '#ea580c',
            cyanColor: '#0891b2',
            mutedAccentColor: '#a1a1aa',
            cardShadow: '0 1px 2px rgba(24, 24, 27, 0.04)',
            elevatedShadow: '0 2px 8px rgba(24, 24, 27, 0.06), 0 12px 32px rgba(24, 24, 27, 0.12)',
            focusRingShadow: '0 0 0 3px rgba(47, 109, 181, 0.22)',
            cardRadius: '10px',
            pillRadius: '999px',
            iconColor: '#2f6db5',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#6366f1',
            categorySolutionColor: '#d97706',
            categoryTechColor: '#dc2626',
            categoryAlgorithmColor: '#2563eb',
            categoryLifeColor: '#16a34a',
            categoryStudyColor: '#9333ea',
            categoryFunColor: '#0d9488',
            categoryChatColor: '#64748b',
            categoryUnknownColor: '#a1a1aa'
        },
        dark: {
            bodyColor: '#0e0e10',
            bodyGradientStart: '#0e0e10',
            bodyGradientEnd: '#0e0e10',
            primaryColor: '#6ba3dd',
            primaryColorHover: '#86b5e5',
            primaryColorPressed: '#5490d0',
            primaryColorSuppl: '#3a6ea8',
            cardColor: '#17171a',
            translucentCardColor: '#17171a',
            cardTitleColor: '#f4f4f5',
            textColor: '#e4e4e7',
            secondaryTextColor: '#b3b3ba',
            mutedTextColor: '#87878f',
            borderColor: '#26262b',
            panelColor: '#1f1f23',
            controlColor: '#1c1c20',
            controlColorFocus: '#202025',
            controlColorDisabled: '#141416',
            controlTextColor: '#e4e4e7',
            controlPlaceholderColor: '#6b6b74',
            controlBorderColor: '#333339',
            controlBorderHoverColor: '#4c4c55',
            controlBorderFocusColor: '#6ba3dd',
            controlTagColor: '#1f1f23',
            controlTagTextColor: '#d4d4d8',
            sliderRailColor: '#2c2c32',
            sliderRailHoverColor: '#38383f',
            sliderFillColor: '#6ba3dd',
            sliderFillHoverColor: '#86b5e5',
            sliderHandleColor: '#f4f4f5',
            backTopColor: '#1f1f23',
            backTopHoverColor: '#26262b',
            backTopIconColor: '#b3b3ba',
            backTopIconHoverColor: '#86b5e5',
            codeBackgroundColor: '#1c1c20',
            codeTextColor: '#f0729e',
            codeTheme: 'dark',
            inlineCodeBackgroundColor: '#1f1f23',
            inlineCodeTextColor: '#f0729e',
            markBackgroundColor: '#1e3250',
            tableHeaderColor: '#1c1c20',
            scrollbarTrackColor: '#17171a',
            scrollbarThumbColor: '#38383f',
            copyButtonBackgroundColor: '#1f1f23',
            copyButtonTextColor: '#d4d4d8',
            footerTextColor: '#87878f',
            linkColor: '#6ba3dd',
            linkHoverColor: '#86b5e5',
            infoColor: '#7cabde',
            successColor: '#4ade80',
            warningColor: '#fbbf24',
            errorColor: '#f87171',
            alertInfoBackgroundColor: '#182335',
            alertSuccessBackgroundColor: '#14281c',
            alertWarningBackgroundColor: '#2c2312',
            alertErrorBackgroundColor: '#2e1818',
            orangeColor: '#fb923c',
            cyanColor: '#22d3ee',
            mutedAccentColor: '#6b6b74',
            cardShadow: '0 1px 2px rgba(0, 0, 0, 0.32)',
            elevatedShadow: '0 2px 8px rgba(0, 0, 0, 0.4), 0 12px 32px rgba(0, 0, 0, 0.5)',
            focusRingShadow: '0 0 0 3px rgba(107, 163, 221, 0.28)',
            cardRadius: '10px',
            pillRadius: '999px',
            iconColor: '#6ba3dd',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#818cf8',
            categorySolutionColor: '#fbbf24',
            categoryTechColor: '#f87171',
            categoryAlgorithmColor: '#60a5fa',
            categoryLifeColor: '#4ade80',
            categoryStudyColor: '#c084fc',
            categoryFunColor: '#2dd4bf',
            categoryChatColor: '#94a3b8',
            categoryUnknownColor: '#a1a1aa'
        }
    },

    recall: {
        name: 'recall',
        label: '追忆',
        light: {
            bodyColor: '#f8fafc',
            bodyGradientStart: '#f8fafc',
            bodyGradientEnd: '#f8fafc',
            primaryColor: '#667eea',
            primaryColorHover: '#7c8cf5',
            primaryColorPressed: '#5568d9',
            primaryColorSuppl: '#9aa8f0',
            cardColor: '#ffffff',
            translucentCardColor: 'rgba(255, 255, 255, 0.82)',
            cardTitleColor: '#2c3e50',
            textColor: '#2c3e50',
            secondaryTextColor: '#555555',
            mutedTextColor: '#888888',
            borderColor: '#e2e8f0',
            panelColor: '#f0f2f5',
            controlColor: '#ffffff',
            controlColorFocus: '#ffffff',
            controlColorDisabled: '#f5f7fa',
            controlTextColor: '#2c3e50',
            controlPlaceholderColor: '#94a3b8',
            controlBorderColor: '#e2e8f0',
            controlBorderHoverColor: '#94a3b8',
            controlBorderFocusColor: '#667eea',
            controlTagColor: '#f1f5f9',
            controlTagTextColor: '#2c3e50',
            sliderRailColor: '#e2e8f0',
            sliderRailHoverColor: '#cbd5e1',
            sliderFillColor: '#667eea',
            sliderFillHoverColor: '#7c8cf5',
            sliderHandleColor: '#ffffff',
            backTopColor: '#ffffff',
            backTopHoverColor: '#f0f2f5',
            backTopIconColor: '#667eea',
            backTopIconHoverColor: '#7c8cf5',
            codeBackgroundColor: '#f1f5f9',
            codeTextColor: '#e11d48',
            codeTheme: 'light',
            inlineCodeBackgroundColor: '#f1f5f9',
            inlineCodeTextColor: '#e11d48',
            markBackgroundColor: 'rgba(102, 126, 234, 0.14)',
            tableHeaderColor: '#f1f5f9',
            scrollbarTrackColor: '#f1f5f9',
            scrollbarThumbColor: '#cbd5e1',
            copyButtonBackgroundColor: 'rgba(255, 255, 255, 0.82)',
            copyButtonTextColor: '#2c3e50',
            footerTextColor: '#2c3e50',
            linkColor: '#337ab7',
            linkHoverColor: '#667eea',
            infoColor: '#7da7ff',
            successColor: '#4dd27a',
            warningColor: '#ffb454',
            errorColor: '#ff5757',
            alertInfoBackgroundColor: 'rgba(125, 167, 255, 0.14)',
            alertSuccessBackgroundColor: 'rgba(77, 210, 122, 0.14)',
            alertWarningBackgroundColor: 'rgba(255, 180, 84, 0.18)',
            alertErrorBackgroundColor: 'rgba(255, 87, 87, 0.12)',
            orangeColor: '#e67e22',
            cyanColor: '#0e90d2',
            mutedAccentColor: '#94a3b8',
            cardShadow: '2px 2px 4px rgba(0, 0, 0, 0.08)',
            elevatedShadow: '0 4px 12px rgba(0, 0, 0, 0.12)',
            focusRingShadow: '0 0 0 3px rgba(102, 126, 234, 0.2)',
            cardRadius: '10px',
            pillRadius: '999px',
            iconColor: '#667eea',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#667eea',
            categorySolutionColor: '#f39c12',
            categoryTechColor: '#e74c3c',
            categoryAlgorithmColor: '#3498db',
            categoryLifeColor: '#2ecc71',
            categoryStudyColor: '#9b59b6',
            categoryFunColor: '#1abc9c',
            categoryChatColor: '#34495e',
            categoryUnknownColor: '#95a5a6'
        },
        dark: {
            bodyColor: '#11141c',
            bodyGradientStart: '#11141c',
            bodyGradientEnd: '#11141c',
            primaryColor: '#818cf8',
            primaryColorHover: '#949dff',
            primaryColorPressed: '#6d78e8',
            primaryColorSuppl: '#515bb5',
            cardColor: '#1a1e2b',
            translucentCardColor: '#1a1e2b',
            cardTitleColor: '#e2e8f0',
            textColor: '#e2e8f0',
            secondaryTextColor: '#a0aec0',
            mutedTextColor: '#718096',
            borderColor: '#2d3348',
            panelColor: '#1f2538',
            controlColor: '#151926',
            controlColorFocus: '#1a1e2b',
            controlColorDisabled: '#0f121c',
            controlTextColor: '#e2e8f0',
            controlPlaceholderColor: '#4a5568',
            controlBorderColor: '#2d3348',
            controlBorderHoverColor: '#4a5568',
            controlBorderFocusColor: '#818cf8',
            controlTagColor: '#1f2538',
            controlTagTextColor: '#cbd5e1',
            sliderRailColor: '#2d3348',
            sliderRailHoverColor: '#3a4158',
            sliderFillColor: '#818cf8',
            sliderFillHoverColor: '#949dff',
            sliderHandleColor: '#e2e8f0',
            backTopColor: '#1f2538',
            backTopHoverColor: '#2d3348',
            backTopIconColor: '#818cf8',
            backTopIconHoverColor: '#949dff',
            codeBackgroundColor: '#151926',
            codeTextColor: '#fb7185',
            codeTheme: 'dark',
            inlineCodeBackgroundColor: '#1a1e2b',
            inlineCodeTextColor: '#fb7185',
            markBackgroundColor: 'rgba(129, 140, 248, 0.16)',
            tableHeaderColor: '#1a1e2b',
            scrollbarTrackColor: '#151926',
            scrollbarThumbColor: '#3a4158',
            copyButtonBackgroundColor: '#1f2538',
            copyButtonTextColor: '#cbd5e1',
            footerTextColor: '#a0aec0',
            linkColor: '#818cf8',
            linkHoverColor: '#949dff',
            infoColor: '#7cabde',
            successColor: '#4ade80',
            warningColor: '#fbbf24',
            errorColor: '#f87171',
            alertInfoBackgroundColor: '#1a2440',
            alertSuccessBackgroundColor: '#14281c',
            alertWarningBackgroundColor: '#2c2312',
            alertErrorBackgroundColor: '#2e1818',
            orangeColor: '#fb923c',
            cyanColor: '#22d3ee',
            mutedAccentColor: '#4a5568',
            cardShadow: '0 2px 4px rgba(0, 0, 0, 0.32)',
            elevatedShadow: '0 4px 12px rgba(0, 0, 0, 0.45)',
            focusRingShadow: '0 0 0 3px rgba(129, 140, 248, 0.25)',
            cardRadius: '10px',
            pillRadius: '999px',
            iconColor: '#818cf8',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#818cf8',
            categorySolutionColor: '#fbbf24',
            categoryTechColor: '#f87171',
            categoryAlgorithmColor: '#60a5fa',
            categoryLifeColor: '#4ade80',
            categoryStudyColor: '#c084fc',
            categoryFunColor: '#2dd4bf',
            categoryChatColor: '#94a3b8',
            categoryUnknownColor: '#94a3b8'
        }
    },

    archive: {
        name: 'archive',
        label: '洛谷仓库',
        light: {
            bodyColor: '#ffffff',
            bodyGradientStart: '#ffffff',
            bodyGradientEnd: '#ffffff',
            primaryColor: '#0f172a',
            primaryColorHover: '#1e293b',
            primaryColorPressed: '#020617',
            primaryColorSuppl: '#475569',
            cardColor: '#ffffff',
            translucentCardColor: 'rgba(255, 255, 255, 0.85)',
            cardTitleColor: '#0f172a',
            textColor: '#0f172a',
            secondaryTextColor: '#475569',
            mutedTextColor: '#64748b',
            borderColor: '#e2e8f0',
            panelColor: '#f1f5f9',
            controlColor: '#ffffff',
            controlColorFocus: '#ffffff',
            controlColorDisabled: '#f8fafc',
            controlTextColor: '#0f172a',
            controlPlaceholderColor: '#94a3b8',
            controlBorderColor: '#e2e8f0',
            controlBorderHoverColor: '#94a3b8',
            controlBorderFocusColor: '#0f172a',
            controlTagColor: '#f1f5f9',
            controlTagTextColor: '#1e293b',
            sliderRailColor: '#e2e8f0',
            sliderRailHoverColor: '#cbd5e1',
            sliderFillColor: '#0f172a',
            sliderFillHoverColor: '#1e293b',
            sliderHandleColor: '#ffffff',
            backTopColor: '#ffffff',
            backTopHoverColor: '#f1f5f9',
            backTopIconColor: '#475569',
            backTopIconHoverColor: '#0f172a',
            codeBackgroundColor: '#f1f5f9',
            codeTextColor: '#be185d',
            codeTheme: 'light',
            inlineCodeBackgroundColor: '#f1f5f9',
            inlineCodeTextColor: '#be185d',
            markBackgroundColor: 'rgba(15, 23, 42, 0.1)',
            tableHeaderColor: '#f8fafc',
            scrollbarTrackColor: '#f1f5f9',
            scrollbarThumbColor: '#cbd5e1',
            copyButtonBackgroundColor: 'rgba(255, 255, 255, 0.85)',
            copyButtonTextColor: '#0f172a',
            footerTextColor: '#64748b',
            linkColor: '#0f172a',
            linkHoverColor: '#1e293b',
            infoColor: '#3b82f6',
            successColor: '#16a34a',
            warningColor: '#d97706',
            errorColor: '#dc2626',
            alertInfoBackgroundColor: 'rgba(59, 130, 246, 0.12)',
            alertSuccessBackgroundColor: 'rgba(22, 163, 74, 0.12)',
            alertWarningBackgroundColor: 'rgba(217, 119, 6, 0.15)',
            alertErrorBackgroundColor: 'rgba(220, 38, 38, 0.1)',
            orangeColor: '#ea580c',
            cyanColor: '#0891b2',
            mutedAccentColor: '#94a3b8',
            cardShadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
            elevatedShadow: '0 4px 16px rgba(0, 0, 0, 0.1)',
            focusRingShadow: '0 0 0 3px rgba(15, 23, 42, 0.12)',
            cardRadius: '16px',
            pillRadius: '999px',
            iconColor: '#0f172a',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#6366f1',
            categorySolutionColor: '#d97706',
            categoryTechColor: '#dc2626',
            categoryAlgorithmColor: '#2563eb',
            categoryLifeColor: '#16a34a',
            categoryStudyColor: '#9333ea',
            categoryFunColor: '#0d9488',
            categoryChatColor: '#64748b',
            categoryUnknownColor: '#94a3b8'
        },
        dark: {
            bodyColor: '#0f172a',
            bodyGradientStart: '#0f172a',
            bodyGradientEnd: '#0f172a',
            primaryColor: '#3b82f6',
            primaryColorHover: '#569df8',
            primaryColorPressed: '#2563eb',
            primaryColorSuppl: '#1d4ed8',
            cardColor: '#1e293b',
            translucentCardColor: '#1e293b',
            cardTitleColor: '#f8fafc',
            textColor: '#f8fafc',
            secondaryTextColor: '#cbd5e1',
            mutedTextColor: '#94a3b8',
            borderColor: 'rgba(255, 255, 255, 0.1)',
            panelColor: 'rgba(255, 255, 255, 0.05)',
            controlColor: '#1a2332',
            controlColorFocus: '#1e293b',
            controlColorDisabled: '#131c28',
            controlTextColor: '#f8fafc',
            controlPlaceholderColor: '#64748b',
            controlBorderColor: 'rgba(255, 255, 255, 0.15)',
            controlBorderHoverColor: 'rgba(255, 255, 255, 0.25)',
            controlBorderFocusColor: '#f8fafc',
            controlTagColor: 'rgba(255, 255, 255, 0.08)',
            controlTagTextColor: '#e2e8f0',
            sliderRailColor: 'rgba(255, 255, 255, 0.15)',
            sliderRailHoverColor: 'rgba(255, 255, 255, 0.2)',
            sliderFillColor: '#f8fafc',
            sliderFillHoverColor: '#e2e8f0',
            sliderHandleColor: '#f8fafc',
            backTopColor: '#1e293b',
            backTopHoverColor: '#2d3a4f',
            backTopIconColor: '#94a3b8',
            backTopIconHoverColor: '#f8fafc',
            codeBackgroundColor: '#1a2332',
            codeTextColor: '#f472b6',
            codeTheme: 'dark',
            inlineCodeBackgroundColor: '#1a2332',
            inlineCodeTextColor: '#f472b6',
            markBackgroundColor: 'rgba(248, 250, 252, 0.12)',
            tableHeaderColor: '#1a2332',
            scrollbarTrackColor: '#1a2332',
            scrollbarThumbColor: '#2d3a4f',
            copyButtonBackgroundColor: '#1e293b',
            copyButtonTextColor: '#e2e8f0',
            footerTextColor: '#94a3b8',
            linkColor: '#e2e8f0',
            linkHoverColor: '#f8fafc',
            infoColor: '#60a5fa',
            successColor: '#4ade80',
            warningColor: '#fbbf24',
            errorColor: '#f87171',
            alertInfoBackgroundColor: 'rgba(96, 165, 250, 0.14)',
            alertSuccessBackgroundColor: 'rgba(74, 222, 128, 0.14)',
            alertWarningBackgroundColor: 'rgba(251, 191, 36, 0.16)',
            alertErrorBackgroundColor: 'rgba(248, 113, 113, 0.14)',
            orangeColor: '#fb923c',
            cyanColor: '#22d3ee',
            mutedAccentColor: '#64748b',
            cardShadow: '0 1px 3px rgba(0, 0, 0, 0.3)',
            elevatedShadow: '0 4px 16px rgba(0, 0, 0, 0.4)',
            focusRingShadow: '0 0 0 3px rgba(248, 250, 252, 0.18)',
            cardRadius: '16px',
            pillRadius: '999px',
            iconColor: '#3b82f6',
            userRedColor: '#e74c3c',
            userOrangeColor: '#e67e22',
            userPurpleColor: '#8e44ad',
            userGreenColor: '#5eb95e',
            userBlueColor: '#0e90d2',
            userGrayColor: '#bbbbbb',
            userCheaterColor: '#996600',
            prizeGreenColor: '#52c41a',
            prizeBlueColor: '#3498db',
            prizeGoldColor: '#ffc116',
            categoryPersonalColor: '#818cf8',
            categorySolutionColor: '#fbbf24',
            categoryTechColor: '#f87171',
            categoryAlgorithmColor: '#60a5fa',
            categoryLifeColor: '#4ade80',
            categoryStudyColor: '#c084fc',
            categoryFunColor: '#2dd4bf',
            categoryChatColor: '#94a3b8',
            categoryUnknownColor: '#94a3b8'
        }
    }
};
