import { type InjectionKey, type Ref } from 'vue';

export type CodeTheme = 'light' | 'dark';
export type UiThemeMode = 'auto' | 'light' | 'dark';
export type UiThemePresetName = 'default' | 'modern' | 'recall' | 'archive';

export interface UiThemeVars {
    bodyColor: string;
    bodyGradientStart: string;
    bodyGradientEnd: string;
    primaryColor: string;
    primaryColorHover: string;
    primaryColorPressed: string;
    primaryColorSuppl: string;
    cardColor: string;
    translucentCardColor: string;
    cardTitleColor: string;
    textColor: string;
    secondaryTextColor: string;
    mutedTextColor: string;
    borderColor: string;
    panelColor: string;
    controlColor: string;
    controlColorFocus: string;
    controlColorDisabled: string;
    controlTextColor: string;
    controlPlaceholderColor: string;
    controlBorderColor: string;
    controlBorderHoverColor: string;
    controlBorderFocusColor: string;
    controlTagColor: string;
    controlTagTextColor: string;
    sliderRailColor: string;
    sliderRailHoverColor: string;
    sliderFillColor: string;
    sliderFillHoverColor: string;
    sliderHandleColor: string;
    backTopColor: string;
    backTopHoverColor: string;
    backTopIconColor: string;
    backTopIconHoverColor: string;
    codeBackgroundColor: string;
    codeTextColor: string;
    codeTheme: CodeTheme;
    inlineCodeBackgroundColor: string;
    inlineCodeTextColor: string;
    markBackgroundColor: string;
    tableHeaderColor: string;
    scrollbarTrackColor: string;
    scrollbarThumbColor: string;
    copyButtonBackgroundColor: string;
    copyButtonTextColor: string;
    footerTextColor: string;
    linkColor: string;
    linkHoverColor: string;
    infoColor: string;
    successColor: string;
    warningColor: string;
    errorColor: string;
    alertInfoBackgroundColor: string;
    alertSuccessBackgroundColor: string;
    alertWarningBackgroundColor: string;
    alertErrorBackgroundColor: string;
    orangeColor: string;
    cyanColor: string;
    mutedAccentColor: string;
    cardShadow: string;
    elevatedShadow: string;
    focusRingShadow: string;
    cardRadius: string;
    pillRadius: string;
    iconColor: string;
    userRedColor: string;
    userOrangeColor: string;
    userPurpleColor: string;
    userGreenColor: string;
    userBlueColor: string;
    userGrayColor: string;
    userCheaterColor: string;
    prizeGreenColor: string;
    prizeBlueColor: string;
    prizeGoldColor: string;
    categoryPersonalColor: string;
    categorySolutionColor: string;
    categoryTechColor: string;
    categoryAlgorithmColor: string;
    categoryLifeColor: string;
    categoryStudyColor: string;
    categoryFunColor: string;
    categoryChatColor: string;
    categoryUnknownColor: string;
}

export const uiThemeKey = Symbol() as InjectionKey<Ref<UiThemeVars>>;
export const uiThemeModeKey = Symbol() as InjectionKey<Ref<UiThemeMode>>;
export const uiThemePresetKey = Symbol() as InjectionKey<Ref<UiThemePresetName>>;
